target_sources_local(Engine
    PRIVATE
    engine/Eyos.cpp
    engine/ecs/EntityId.cpp
    engine/Terrain.cpp
    engine/Time.cpp
    engine/net/Address.cpp
    engine/net/Net.cpp
    engine/net/Peer.cpp
    engine/net/Host.cpp
    engine/net/Packet.cpp
    engine/net/NetEventHandler.cpp
    engine/net/Common.cpp
    engine/net/streams/InputStream.cpp
    engine/net/streams/OutputStream.cpp
    engine/net/Allocator.cpp
    engine/gen/PerlinNoise.cpp
    engine/gen/Image.cpp
    engine/gen/MapGeneration.cpp
    engine/gen/FlowField.cpp
    engine/ecs/MTP_Utils.cpp
    engine/nav/TerrainNav.cpp
)