target_sources_local(Engine
    PRIVATE
    engine/Eyos.cpp
	engine/ecs/EntityId.cpp
    engine/Terrain.cpp
    engine/net/Address.cpp
    engine/net/Net.cpp
    engine/net/Peer.cpp
    engine/net/Host.cpp
    engine/net/Packet.cpp
    engine/net/NetEventHandler.cpp
    engine/net/Common.cpp
)