name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update cmake
      run: wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz &&  tar xvzf cmake-3.16.2-Linux-x86_64.tar.gz && cd 
    - name: configure
      run: ls && cmake -DBUILD_TESTING=ON .
    - name: ctest
      run: ctest .
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
