name: C/C++ CI Linux

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: update cmake
      run: wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz &&  tar xvzf cmake-3.16.2-Linux-x86_64.tar.gz
    - name: install openGL
      run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: create smlink
      run: cmake-3.16.2-Linux-x86_64/bin/cmake cm && chmod 777 cm
    - name: Install correct version of gcc
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install gcc-9 g++-9 && sudo apt-get install --reinstall libpthread-stubs0-dev
    - name: configure
      run: ./cm .
    - name: make Engine
      run: make -j4 Engine
    - name: make DedicatedServer
      run: make -j4 EyosDedicatedServer
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
