name: C/C++ Build Linux (gcc9)

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: update cmake
      run: wget https://github.com/Kitware/CMake/releases/download/v3.16.2/cmake-3.16.2-Linux-x86_64.tar.gz &&  tar xvzf cmake-3.16.2-Linux-x86_64.tar.gz
    - name: create smlink
      run: ln -s cmake-3.16.2-Linux-x86_64/bin/cmake cm && chmod 777 cm
    - name: Install correct version of gcc
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt install gcc-9 g++-9 && sudo apt-get install --reinstall libpthread-stubs0-dev
    - name: install openGL
      run: sudo apt-get install libglu1-mesa-dev freeglut3-dev mesa-common-dev
    - name: configure
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9 && sudo  chmod  777 tools/* && mkdir build && cd build && ./../cm  -DBUILD_ASSETS=OFF ..
    - name: make tools
      run: cd build && make -j4 tools && make -j4 texturec && make -j4 texturev && make -j4 shaderc && make -j4 geometryc
    - name: make Engine
      run: cd build && make -j4 Engine
    - name: make Eyos
      run: cd build && make -j4 Eyos
